name: unlimit_task
description: Demo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2  # Cupertino-style icons for iOS.

  get: ^4.6.5  # State management and navigation library.
  dio: ^5.3.2   # HTTP client for making network requests.
  equatable: ^2.0.5  # Helps with implementing equality and hashcode for objects.
  shared_preferences: ^2.2.1  # Provides a way to persistently store simple data.

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0  # A set of recommended lints for good coding practices.

flutter:
  uses-material-design: true
